version: "2"
plugins:
  eslint:
    enabled: false
checks:
  complex-logic:
    enabled: true
    config:
      threshold: 8
  method-lines:
    enabled: true
    config:
      threshold: 40
  similar-code:
    enabled: false
exclude_patterns:
- "*"
- "flow-typed/"
- "keymaps/"
- "node_modules/"
- "spec/"
- "styles/"
