// flow-typed signature: f312940f73ba81005c6260cbfa6ef6ea
// flow-typed version: <<STUB>>/atom-babel6-transpiler_v1.1.3/flow_v0.65.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'atom-babel6-transpiler'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'atom-babel6-transpiler' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'atom-babel6-transpiler/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'atom-babel6-transpiler/lib/index.js' {
  declare module.exports: $Exports<'atom-babel6-transpiler/lib/index'>;
}
