// flow-typed signature: bb508d7361ed1ce833ae363ef2d598ba
// flow-typed version: <<STUB>>/babel-plugin-transform-regenerator_v^6.26.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-plugin-transform-regenerator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-plugin-transform-regenerator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-plugin-transform-regenerator/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-plugin-transform-regenerator/lib/index.js' {
  declare module.exports: $Exports<'babel-plugin-transform-regenerator/lib/index'>;
}
