// flow-typed signature: 937aa27c3f08e4c5cb05340b46983c17
// flow-typed version: <<STUB>>/bson_v3.0.0/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bson/dist/bson' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/binary' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/bson' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/code' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/db_ref' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/decimal128' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/double' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/float_parser' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/fnv1a' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/int_32' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/long' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/map' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/max_key' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/min_key' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/objectid' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/parser/calculate_size' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/parser/deserializer' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/parser/serializer' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/parser/utils' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/regexp' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/symbol' {
  declare module.exports: any;
}

declare module 'bson/lib/bson/timestamp' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bson/dist/bson.js' {
  declare module.exports: $Exports<'bson/dist/bson'>;
}
declare module 'bson/index' {
  declare module.exports: $Exports<'bson'>;
}
declare module 'bson/index.js' {
  declare module.exports: $Exports<'bson'>;
}
declare module 'bson/lib/bson/binary.js' {
  declare module.exports: $Exports<'bson/lib/bson/binary'>;
}
declare module 'bson/lib/bson/bson.js' {
  declare module.exports: $Exports<'bson/lib/bson/bson'>;
}
declare module 'bson/lib/bson/code.js' {
  declare module.exports: $Exports<'bson/lib/bson/code'>;
}
declare module 'bson/lib/bson/db_ref.js' {
  declare module.exports: $Exports<'bson/lib/bson/db_ref'>;
}
declare module 'bson/lib/bson/decimal128.js' {
  declare module.exports: $Exports<'bson/lib/bson/decimal128'>;
}
declare module 'bson/lib/bson/double.js' {
  declare module.exports: $Exports<'bson/lib/bson/double'>;
}
declare module 'bson/lib/bson/float_parser.js' {
  declare module.exports: $Exports<'bson/lib/bson/float_parser'>;
}
declare module 'bson/lib/bson/fnv1a.js' {
  declare module.exports: $Exports<'bson/lib/bson/fnv1a'>;
}
declare module 'bson/lib/bson/int_32.js' {
  declare module.exports: $Exports<'bson/lib/bson/int_32'>;
}
declare module 'bson/lib/bson/long.js' {
  declare module.exports: $Exports<'bson/lib/bson/long'>;
}
declare module 'bson/lib/bson/map.js' {
  declare module.exports: $Exports<'bson/lib/bson/map'>;
}
declare module 'bson/lib/bson/max_key.js' {
  declare module.exports: $Exports<'bson/lib/bson/max_key'>;
}
declare module 'bson/lib/bson/min_key.js' {
  declare module.exports: $Exports<'bson/lib/bson/min_key'>;
}
declare module 'bson/lib/bson/objectid.js' {
  declare module.exports: $Exports<'bson/lib/bson/objectid'>;
}
declare module 'bson/lib/bson/parser/calculate_size.js' {
  declare module.exports: $Exports<'bson/lib/bson/parser/calculate_size'>;
}
declare module 'bson/lib/bson/parser/deserializer.js' {
  declare module.exports: $Exports<'bson/lib/bson/parser/deserializer'>;
}
declare module 'bson/lib/bson/parser/serializer.js' {
  declare module.exports: $Exports<'bson/lib/bson/parser/serializer'>;
}
declare module 'bson/lib/bson/parser/utils.js' {
  declare module.exports: $Exports<'bson/lib/bson/parser/utils'>;
}
declare module 'bson/lib/bson/regexp.js' {
  declare module.exports: $Exports<'bson/lib/bson/regexp'>;
}
declare module 'bson/lib/bson/symbol.js' {
  declare module.exports: $Exports<'bson/lib/bson/symbol'>;
}
declare module 'bson/lib/bson/timestamp.js' {
  declare module.exports: $Exports<'bson/lib/bson/timestamp'>;
}
