// flow-typed signature: cbf594c0de518b2d06c706203a796048
// flow-typed version: <<STUB>>/bson_v4.0.0/flow_v0.86.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'bson'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'bson' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'bson/dist/bson.browser.esm' {
  declare module.exports: any;
}

declare module 'bson/dist/bson.browser.umd' {
  declare module.exports: any;
}

declare module 'bson/dist/bson.bundle' {
  declare module.exports: any;
}

declare module 'bson/dist/bson.esm' {
  declare module.exports: any;
}

declare module 'bson/lib/binary' {
  declare module.exports: any;
}

declare module 'bson/lib/bson' {
  declare module.exports: any;
}

declare module 'bson/lib/code' {
  declare module.exports: any;
}

declare module 'bson/lib/constants' {
  declare module.exports: any;
}

declare module 'bson/lib/db_ref' {
  declare module.exports: any;
}

declare module 'bson/lib/decimal128' {
  declare module.exports: any;
}

declare module 'bson/lib/double' {
  declare module.exports: any;
}

declare module 'bson/lib/ensure_buffer' {
  declare module.exports: any;
}

declare module 'bson/lib/extended_json' {
  declare module.exports: any;
}

declare module 'bson/lib/float_parser' {
  declare module.exports: any;
}

declare module 'bson/lib/fnv1a' {
  declare module.exports: any;
}

declare module 'bson/lib/int_32' {
  declare module.exports: any;
}

declare module 'bson/lib/long' {
  declare module.exports: any;
}

declare module 'bson/lib/map' {
  declare module.exports: any;
}

declare module 'bson/lib/max_key' {
  declare module.exports: any;
}

declare module 'bson/lib/min_key' {
  declare module.exports: any;
}

declare module 'bson/lib/objectid' {
  declare module.exports: any;
}

declare module 'bson/lib/parser/calculate_size' {
  declare module.exports: any;
}

declare module 'bson/lib/parser/deserializer' {
  declare module.exports: any;
}

declare module 'bson/lib/parser/serializer' {
  declare module.exports: any;
}

declare module 'bson/lib/parser/utils' {
  declare module.exports: any;
}

declare module 'bson/lib/regexp' {
  declare module.exports: any;
}

declare module 'bson/lib/symbol' {
  declare module.exports: any;
}

declare module 'bson/lib/timestamp' {
  declare module.exports: any;
}

declare module 'bson/lib/validate_utf8' {
  declare module.exports: any;
}

// Filename aliases
declare module 'bson/dist/bson.browser.esm.js' {
  declare module.exports: $Exports<'bson/dist/bson.browser.esm'>;
}
declare module 'bson/dist/bson.browser.umd.js' {
  declare module.exports: $Exports<'bson/dist/bson.browser.umd'>;
}
declare module 'bson/dist/bson.bundle.js' {
  declare module.exports: $Exports<'bson/dist/bson.bundle'>;
}
declare module 'bson/dist/bson.esm.js' {
  declare module.exports: $Exports<'bson/dist/bson.esm'>;
}
declare module 'bson/lib/binary.js' {
  declare module.exports: $Exports<'bson/lib/binary'>;
}
declare module 'bson/lib/bson.js' {
  declare module.exports: $Exports<'bson/lib/bson'>;
}
declare module 'bson/lib/code.js' {
  declare module.exports: $Exports<'bson/lib/code'>;
}
declare module 'bson/lib/constants.js' {
  declare module.exports: $Exports<'bson/lib/constants'>;
}
declare module 'bson/lib/db_ref.js' {
  declare module.exports: $Exports<'bson/lib/db_ref'>;
}
declare module 'bson/lib/decimal128.js' {
  declare module.exports: $Exports<'bson/lib/decimal128'>;
}
declare module 'bson/lib/double.js' {
  declare module.exports: $Exports<'bson/lib/double'>;
}
declare module 'bson/lib/ensure_buffer.js' {
  declare module.exports: $Exports<'bson/lib/ensure_buffer'>;
}
declare module 'bson/lib/extended_json.js' {
  declare module.exports: $Exports<'bson/lib/extended_json'>;
}
declare module 'bson/lib/float_parser.js' {
  declare module.exports: $Exports<'bson/lib/float_parser'>;
}
declare module 'bson/lib/fnv1a.js' {
  declare module.exports: $Exports<'bson/lib/fnv1a'>;
}
declare module 'bson/lib/int_32.js' {
  declare module.exports: $Exports<'bson/lib/int_32'>;
}
declare module 'bson/lib/long.js' {
  declare module.exports: $Exports<'bson/lib/long'>;
}
declare module 'bson/lib/map.js' {
  declare module.exports: $Exports<'bson/lib/map'>;
}
declare module 'bson/lib/max_key.js' {
  declare module.exports: $Exports<'bson/lib/max_key'>;
}
declare module 'bson/lib/min_key.js' {
  declare module.exports: $Exports<'bson/lib/min_key'>;
}
declare module 'bson/lib/objectid.js' {
  declare module.exports: $Exports<'bson/lib/objectid'>;
}
declare module 'bson/lib/parser/calculate_size.js' {
  declare module.exports: $Exports<'bson/lib/parser/calculate_size'>;
}
declare module 'bson/lib/parser/deserializer.js' {
  declare module.exports: $Exports<'bson/lib/parser/deserializer'>;
}
declare module 'bson/lib/parser/serializer.js' {
  declare module.exports: $Exports<'bson/lib/parser/serializer'>;
}
declare module 'bson/lib/parser/utils.js' {
  declare module.exports: $Exports<'bson/lib/parser/utils'>;
}
declare module 'bson/lib/regexp.js' {
  declare module.exports: $Exports<'bson/lib/regexp'>;
}
declare module 'bson/lib/symbol.js' {
  declare module.exports: $Exports<'bson/lib/symbol'>;
}
declare module 'bson/lib/timestamp.js' {
  declare module.exports: $Exports<'bson/lib/timestamp'>;
}
declare module 'bson/lib/validate_utf8.js' {
  declare module.exports: $Exports<'bson/lib/validate_utf8'>;
}
