// flow-typed signature: 2780bc9644c474cb52e3b0fc3a88817c
// flow-typed version: <<STUB>>/fs-plus_v3.0.1/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fs-plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fs-plus' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fs-plus/lib/fs-plus' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fs-plus/lib/fs-plus.js' {
  declare module.exports: $Exports<'fs-plus/lib/fs-plus'>;
}
