// flow-typed signature: 80d94e76d985eadc4a71354e9d6ce937
// flow-typed version: <<STUB>>/sifter_v0.5.2/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sifter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sifter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sifter/bin/sifter' {
  declare module.exports: any;
}

declare module 'sifter/lib/sifter' {
  declare module.exports: any;
}

declare module 'sifter/sifter' {
  declare module.exports: any;
}

declare module 'sifter/sifter.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sifter/bin/sifter.js' {
  declare module.exports: $Exports<'sifter/bin/sifter'>;
}
declare module 'sifter/lib/sifter.js' {
  declare module.exports: $Exports<'sifter/lib/sifter'>;
}
declare module 'sifter/sifter.js' {
  declare module.exports: $Exports<'sifter/sifter'>;
}
declare module 'sifter/sifter.min.js' {
  declare module.exports: $Exports<'sifter/sifter.min'>;
}
