// flow-typed signature: ba7220cf5091736e8a437f83c6907048
// flow-typed version: <<STUB>>/tempy_v0.2.1/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tempy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tempy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'tempy/index' {
  declare module.exports: $Exports<'tempy'>;
}
declare module 'tempy/index.js' {
  declare module.exports: $Exports<'tempy'>;
}
